### ISSUE TITLE
Window opens up blank in Electron 5.0

### ISSUE THREAD

**Issue by grantcv1** [getstation/electron-process-manager#17]
The problem is that nodeIntegration defaults to false in Electron 5.0. Setting nodeIntegration to true in the webPreferences option when constructing the ProcessManagerWindow (extending BrowserWindow) seems to rectify that problem.

**Comment by hugomano** [comment]
https://github.com/getstation/electron-process-manager/pull/18

**Comment by hugomano** [comment]
@grantcv1 fixed with `v0.7.1` 😄
