### ISSUE TITLE
Memoize misspelled

### ISSUE THREAD

**Issue by zekenie** [getstation/electron-process-manager#4]
`const memoize = require("memoizee");` in `src/ProcessStatsReporter.js`

:)

**Comment by alexstrat** [comment]
Are you sure it's a mistake? If you you talking about `"memoizee"`, it's actually a real package that i'm using => https://github.com/medikoo/memoizee

**Comment by zekenie** [comment]
Ah, good question. I thought it was a mistake because when I ran my app after installing `electron-process-manager` with yarn, it told me that `memoizee` was missing. It looked like a typo so I figured it was... not sure what's going on in that case

**Comment by alexstrat** [comment]
I may have forgotten a dependency.

Can you try with `npm install electron-process-manager@0.3.0` ?

**Comment by zekenie** [comment]
I think this is solved. I don't remember what exactly was going on
